# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Firezip.Firezip
PackageVersion: 1.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-
UpgradeBehavior: install
FileExtensions:
- zip
- 7z
- rar
- tar
- gz
- bz2
ProductCode: '{8B036367-AE8C-4D88-B1F3-E18F2E23A534}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/drodrigues55/firezip/releases/download/v1.0.0/FirezipSetup-x64-v1.0.0.exe
  InstallerSha256: C0EA4372C835D3B3AD3773306B5997084A7AED50A947234F04256C9132B8C17B
ManifestType: installer
ManifestVersion: 1.9.0
